version=1.1.5-SNAPSHOT
kotlin.code.style=official
restAssuredVersion=5.5.6
springDataJdbcPlusVersion=3.5.7
grpcVersion=1.68.0
grpcKotlinVersion=1.4.1
protobufVersion=3.25.3
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
#signing.keyId=YourKeyId
#signing.password=YourPublicKeyPassword
#signing.secretKeyRingFile=PathToYourKeyRingFile
#ossrhUsername=your-jira-id
#ossrhPassword=your-jira-password
