serverUrl=http://localhost:8080
apiKey=05d5ee23-858c-4564-8532-db75d59a4592
appName=demo
packages=com.example.demo
annotations=@com.example.demo.annotation.ScavengerEnabled, @org.springframework.web.bind.annotation.RestController, @org.springframework.web.bind.annotation.Controller, @org.springframework.stereotype.Service
additionalPackages=com.example.demo.additional, com.example.demo.extmodel
excludeByRegex=^com\.example\.demo\.service\..*TestRegex.*$
methodVisibility = protected
excludeConstructors = true
environment = test
forceIntervalSeconds = 10
debugMode = true
callStackTraceMode = true
